view: dim_territorio {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `dim_territorio` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.dim_territorio` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  dimension: dimension_key {
    label: "DIMENSION_KEY"
    type: number
    sql: ${TABLE}.dimension_key ;;
    primary_key: yes
    hidden: yes
    description: "Surrogate join key (R6.4). primary_key is the fanout guard that lets Looker skip symmetric aggregates (R6.2). Sentinel dimension_key = 0 means Desconocido/a member — a real member, not missing data (RULEBOOK R5.1)."
  }
  dimension: residencia_ccaa_codigo {
    label: "Residencia CCAA código"
    type: string
    sql: ${TABLE}.ccaa_codigo ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_ccaa_nombre {
    label: "Residencia CCAA nombre"
    type: string
    sql: ${TABLE}.ccaa_nombre ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_provincia_codigo {
    label: "Residencia provincia código"
    type: string
    sql: ${TABLE}.provincia_codigo ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_provincia_nombre {
    label: "Residencia provincia nombre"
    type: string
    sql: ${TABLE}.provincia_nombre ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_comarca_codigo {
    label: "Residencia comarca código"
    type: string
    sql: ${TABLE}.comarca_codigo ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_comarca_nombre {
    label: "Residencia comarca nombre"
    type: string
    sql: ${TABLE}.comarca_nombre ;;
    view_label: "Lugar de Residencia"
    description: "Sentinel comarca_nombre = 'Sin definir' means no comarca — a real member, not missing data (RULEBOOK R5.1)."
  }
  dimension: residencia_municipio_codigo {
    label: "Residencia municipio código"
    type: string
    sql: ${TABLE}.municipio_codigo ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_municipio_nombre {
    label: "Residencia municipio nombre"
    type: string
    sql: ${TABLE}.nombre_actual ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_municipio_nombre_historico {
    label: "Residencia municipio nombre historico"
    type: string
    sql: ${TABLE}.municipio_descripcion ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_municipio_montana {
    label: "Residencia municipio montaña"
    type: string
    sql: ${TABLE}.municipio_montana ;;
    view_label: "Lugar de Residencia"
    description: "Sentinel municipio_montana = '-1' means unknown, stored as the string '-1' — a real member, not missing data (RULEBOOK R5.1)."
  }
  dimension: residencia_municipio_zona_desfavorecida {
    label: "Residencia municipio zona desfavorecida"
    type: string
    sql: ${TABLE}.municipio_zona_desf ;;
    view_label: "Lugar de Residencia"
  }
  dimension: municipio_estrato {
    label: "Municipio estrato"
    type: number
    sql: ${TABLE}.estrato ;;
    view_label: "Lugar de Residencia"
  }
  dimension: municipio_estrato_desc {
    label: "Municipio estrato desc"
    type: string
    sql: CASE ${TABLE}.estrato WHEN 1 THEN 'Menos de 100' WHEN 2 THEN 'De 100 a 499' WHEN 3 THEN 'De 500 a 999' WHEN 4 THEN 'De 1000 a 4999' WHEN 5 THEN 'De 5000 a 9999' WHEN 6 THEN 'De 10000 a 29999' WHEN 7 THEN '30000 ó más hab' END ;;
    view_label: "Lugar de Residencia"
    description: "OBIEE expression: CASE Municipio estrato WHEN 1 THEN 'Menos de 100' WHEN 2 THEN 'De 100 a 499' WHEN 3 THEN 'De 500 a 999' WHEN 4 THEN 'De 1000 a 4999' WHEN 5 THEN 'De 5000 a 9999' WHEN 6 THEN 'De 10000 a 29999' WHEN 7 THEN '30000 ó más hab' END."
  }
  dimension: municipio_poblacion {
    label: "Municipio población"
    type: number
    sql: ${TABLE}.poblacion ;;
    view_label: "Lugar de Residencia"
  }
  dimension: fecha_inicio {
    label: "Fecha inicio"
    type: date
    sql: ${TABLE}.fecha_ini ;;
    datatype: date
    view_label: "Lugar de Residencia"
    hidden: yes
    description: "Unpopulated SCD column: FECHA_INI is 01/01/01 on 7,377 rows and every FECHA_FIN is 01/01/00. Parsed faithfully, hidden rather than exposed as junk (R8.2)."
  }
  dimension: fecha_fin {
    label: "Fecha fin"
    type: date
    sql: ${TABLE}.fecha_fin ;;
    datatype: date
    view_label: "Lugar de Residencia"
    hidden: yes
    description: "Unpopulated SCD column: FECHA_INI is 01/01/01 on 7,377 rows and every FECHA_FIN is 01/01/00. Parsed faithfully, hidden rather than exposed as junk (R8.2)."
  }
  dimension: actual {
    label: "Actual"
    type: number
    sql: ${TABLE}.actual ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_municipio_estrato_afiliacion {
    label: "Residencia municipio estrato afiliacion"
    type: number
    sql: ${TABLE}.estrato_afiliacion ;;
    view_label: "Lugar de Residencia"
  }
  dimension: residencia_municipio_num_afiliaciones {
    label: "Residencia municipio num afiliaciones"
    type: number
    sql: ${TABLE}.num_afiliaciones ;;
    view_label: "Lugar de Residencia"
  }
  dimension: comarca_superficie_codigo {
    label: "Comarca superficie código"
    type: number
    sql: ${TABLE}.comarca_superficie ;;
    hidden: yes
    description: "No OBIEE presentation folder exposes this column, so it stays out of the field picker (R8.5)."
  }
  dimension: municipio_superficie_codigo {
    label: "Municipio superficie código"
    type: number
    sql: ${TABLE}.municipio_superficie ;;
    hidden: yes
    description: "No OBIEE presentation folder exposes this column, so it stays out of the field picker (R8.5). Sentinel municipio_superficie = -1 means area unknown — 7,635 of 8,376 rows, all outside Aragón — a real member, not missing data (RULEBOOK R5.1, R4.3). Sentinel municipio_superficie = 0 means data-quality hole — 5 rows incl. Maleján (in the fact) — a real member, not missing data (RULEBOOK R4.4 / BLK-006)."
  }
  dimension: provincia_superficie_codigo {
    label: "Provincia superficie código"
    type: number
    sql: ${TABLE}.provincia_superficie ;;
    hidden: yes
    description: "No OBIEE presentation folder exposes this column, so it stays out of the field picker (R8.5)."
  }
  # R7.1 — drill chain Residencia CCAA nombre → Residencia provincia nombre → Residencia municipio nombre.
  # Default chain on the measures.
  set: drill_administrativo {
    fields: [residencia_ccaa_nombre, residencia_provincia_nombre, residencia_municipio_nombre]
  }
  # R7.1 — drill chain Residencia CCAA nombre → Residencia comarca nombre → Residencia municipio nombre.
  # Available, not the default.
  # COMARCA_NOMBRE is 'Sin definir' for 91% of the dimension, which is why this is not the default.
  set: drill_comarcal {
    fields: [residencia_ccaa_nombre, residencia_comarca_nombre, residencia_municipio_nombre]
  }
  measure: superficie_municipio {
    # R4.1/R4.2 — `sum_distinct` keyed at the municipio level (municipio_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.municipio_codigo ;;
    sql: ${TABLE}.municipio_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_municipio_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the municipio level (municipio_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.municipio_codigo ;;
    sql: ${TABLE}.municipio_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_comarca {
    # R4.1/R4.2 — `sum_distinct` keyed at the comarca level (comarca_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.comarca_codigo ;;
    sql: ${TABLE}.comarca_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_comarca_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the comarca level (comarca_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.comarca_codigo ;;
    sql: ${TABLE}.comarca_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_provincia {
    # R4.1/R4.2 — `sum_distinct` keyed at the provincia level (provincia_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_codigo ;;
    sql: ${TABLE}.provincia_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_provincia_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the provincia level (provincia_codigo), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_codigo ;;
    sql: ${TABLE}.provincia_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_aragon {
    # R4.1/R4.2 — `sum_distinct` keyed at the aragon level (provincia_superficie_km2), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    # R4.0 — this is the logical column `Aragón superficie código`, whose physical
    # mapping is SUM(DISTINCT(PROVINCIA_SUPERFICIE)): an aggregate declared on a
    # dimension table, so it is a measure. R4.3 — OBIEE leaves it unscoped over the
    # whole 20-CCAA dimension, which is the one place the -1 sentinel leaks (47,720
    # vs 47,721 km²). The distinct key is the area column itself, not ccaa_codigo:
    # OBIEE's DISTINCT is on the value, and keying on ccaa_codigo counts the -1
    # once per CCAA that carries it (18x), giving 47,703 — neither ruling. Departs
    # from R4.2's table on purpose; see the generator docstring.
    description: "Guarded denominator: area sentinels -1 and 0 are removed row-level in mart.dim_territorio — RULEBOOK R4.1, R4.2, R4.3 (null), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_superficie_km2 ;;
    sql: ${TABLE}.provincia_superficie_km2 ;;
    value_format_name: decimal_0
    hidden: yes
  }
  measure: superficie_aragon_raw {
    # R4.1/R4.2 — `sum_distinct` keyed at the aragon level (provincia_superficie_km2_obiee), never dimension_key.
    # R4.6 — reads the pre-guarded mart column. The sentinel is nulled row-level in
    # dbt, one step before any aggregation, so this file carries no sentinel handling
    # at all — which is what makes R4.4's misplacement bug unexpressible here.
    # R4.0 — this is the logical column `Aragón superficie código`, whose physical
    # mapping is SUM(DISTINCT(PROVINCIA_SUPERFICIE)): an aggregate declared on a
    # dimension table, so it is a measure. R4.3 — OBIEE leaves it unscoped over the
    # whole 20-CCAA dimension, which is the one place the -1 sentinel leaks (47,720
    # vs 47,721 km²). The distinct key is the area column itself, not ccaa_codigo:
    # OBIEE's DISTINCT is on the value, and keying on ccaa_codigo counts the -1
    # once per CCAA that carries it (18x), giving 47,703 — neither ruling. Departs
    # from R4.2's table on purpose; see the generator docstring.
    description: "BUG(port): keeps SUPERFICIE = -1 in the denominator, exactly as OBIEE does — RULEBOOK R4.3 (bug_port), R4.6"
    type: sum_distinct
    sql_distinct_key: ${TABLE}.provincia_superficie_km2_obiee ;;
    sql: ${TABLE}.provincia_superficie_km2_obiee ;;
    value_format_name: decimal_0
    hidden: yes
  }
}
