view: dim_edad {
  # Generated by tools/gen_lookml.py from migration/ir/model.json.
  # Do not edit by hand; edit the generator or the IR.
  # Binds to the dbt mart relation `dim_edad` (RULEBOOK R1.1).
  sql_table_name: `@{gcp_project}.@{dataset_mart}.dim_edad` ;;
  # Dimensions, dimension_groups and drill sets — RULEBOOK R5, R7, R8.
  # view_label mirrors the OBIEE presentation folder that exposes each field
  # (R8.5); a logical column no folder exposes is hidden — it is plumbing.
  dimension: dimension_key {
    label: "DIMENSION_KEY"
    type: number
    sql: ${TABLE}.dimension_key ;;
    primary_key: yes
    hidden: yes
    description: "Surrogate join key (R6.4). primary_key is the fanout guard that lets Looker skip symmetric aggregates (R6.2)."
  }
  dimension: edad_anno_anno {
    label: "Edad (año a año)"
    type: number
    sql: ${TABLE}.edad ;;
    view_label: "Edad y Sexo"
    description: "Sentinel edad = -1 means Desconocido/a — a real member, not missing data (RULEBOOK R5.1, R5.3)."
  }
  dimension: edad_hasta_95 {
    label: "Edad (hasta 95)"
    type: string
    sql: CASE WHEN ${TABLE}.edad >= 95 THEN '95 y más' WHEN ${TABLE}.edad < 10 THEN CONCAT('0', CAST(${TABLE}.edad AS STRING)) ELSE CAST(${TABLE}.edad AS STRING) END ;;
    view_label: "Edad y Sexo"
    description: "OBIEE expression: CASE WHEN EDAD >= 95 THEN '95 y más' WHEN EDAD < 10 THEN CONCAT('0', CAST(EDAD AS VARCHAR(10))) ELSE CAST(EDAD AS VARCHAR(10)) END. Sentinel edad = -1 means Desconocido/a — a real member, not missing data (RULEBOOK R5.1, R5.3)."
  }
  dimension: edad_grupos_quinquenales {
    label: "Edad (grupos quinquenales)"
    type: string
    sql: ${TABLE}.grupos_quinquenales ;;
    view_label: "Edad y Sexo"
  }
  dimension: edad_grandes_grupos {
    label: "Edad (grandes grupos)"
    type: string
    sql: ${TABLE}.grandes_grupos ;;
    view_label: "Edad y Sexo"
  }
  # R7.2 — drill chain Edad (grandes grupos) → Edad (grupos quinquenales) → Edad (año a año).
  # Default chain on the measures.
  set: drill_edad {
    fields: [edad_grandes_grupos, edad_grupos_quinquenales, edad_anno_anno]
  }
}
